//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLibPractice.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicLibraryEntities : DbContext
    {
        public MusicLibraryEntities()
            : base("name=MusicLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<albums> albums { get; set; }
        public virtual DbSet<authors> authors { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<formats> formats { get; set; }
        public virtual DbSet<genres> genres { get; set; }
        public virtual DbSet<paths> paths { get; set; }
        public virtual DbSet<songs> songs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
