//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicLibPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class songs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public songs()
        {
            this.albums = new HashSet<albums>();
        }
    
        public int song_id { get; set; }
        public Nullable<int> format_id { get; set; }
        public Nullable<int> path_id { get; set; }
        public Nullable<int> genre_id { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> duration { get; set; }
        public string song_name { get; set; }
        public Nullable<int> song_date { get; set; }
        public Nullable<int> country_id { get; set; }
    
        public virtual authors authors { get; set; }
        public virtual countries countries { get; set; }
        public virtual formats formats { get; set; }
        public virtual genres genres { get; set; }
        public virtual paths paths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<albums> albums { get; set; }
    }
}
